baseURL = 'https://jakesimonds.github.io'
languageCode = 'en-us'

theme = 'hugo-paper'

[params]
    color = 'linen'
    github = 'jakesimonds'
    linkedin = 'jake-simonds'

    
    name = 'Jake Simonds'
    bio = 'Hello'

    # Direct image link format for Imgur
    avatar = 'https://imgur.com/yMxh4fk.jpg'


[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
[[menu.main]]
    name = 'Calendly'
    identifier = "Chat"
    url = "https://calendly.com/jakesimonds/30min" 
    weight = 40
[[menu.main]]
    name = 'Info'
    url = '#'
    weight = 25
    [menu.main.params]
        modal_trigger = true
